source 'https://rubygems.org'

gem 'foreman'
gem 'rack'
gem 'sinatra'
gem 'thin'
gem 'sinatra-contrib'
gem 'json','1.5.4'
gem 'haml'
gem 'sass'
gem 'data_mapper'
gem 'dm-types','>=1.2.0'
gem 'dm-mysql-adapter','>=1.2.0'
